name: Deploy to GitHub Pages
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build elm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up elm
        uses: justgook/setup-elm@v1
      - name: Move files
        run: mv "./src/static" "./build"
      - name: Elm Make
        run: elm make --optimize --output="./build/bundle.src.js" src/Main.elm
      - name: Uglify-js
        run: npx uglify-js "./build/bundle.src.js" --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | npx uglify-js --mangle --output="./build/bundle.js"
      - name: Remove redundant file
        run: rm ./build/bundle.src.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.7.0-1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build
        with:
          emptyCommits: false
