name: Deploy to GitHub Pages
on:
  push:
    branches:
    - dev

jobs:
  build:
    name: Build elm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up elm
        uses: justgook/setup-elm@v1
      - name: Elm Make
        run: elm make src/Main.elm
      - name: Remove sources
        run: |
          rm -rf src
          rm -rf elm-stuff
          rm -rf .github
          rm -f .gitignore
          rm -f README.md
          rm -f elm.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # EXTERNAL_REPOSITORY: vladimirlogachev/vladimirlogachev.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: .
        with:
          emptyCommits: false
          # keepFiles: true