name: Deploy to GitHub Pages
on:
  push:
    branches:
    - dev

jobs:
  build:
    name: Build elm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up elm
        uses: justgook/setup-elm@v1
      - name: Elm Make
        run: elm make src/Main.elm
      - name: Move files
        run: |
          mkdir ./public
          mv ./index.html ./public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.7.0-1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
        with:
          emptyCommits: false
